### PR TITLE
Fix filter callbacks

### PR DESCRIPTION
**Pull request by jazzsequence**
Use actual callback functions so the filters work. 🤦‍♂️

Related to humanmade/altis-consent#25

### CODE REVIEW

**Review by roborourke — APPROVED** [review]
You know I actually wish this kind of thing was doable wherever you just wanted to hardcode a return value!

**Comment by jazzsequence** [comment]
this is like the second time I've looked back on my code and realized I did that. It would definitely save me from myself if it was a thing you could just do. 😅

**Comment by roborourke** [comment]
Looking at this again and I'm not sure now why this was actually needed - with `apply_filters()` you don't need to use a callback, that's only for `add_filter()`. Could it be that there was some other issue making you think these filters weren't working?

**Comment by jazzsequence** [comment]
From http://developer.wordpress.org/reference/functions/apply_filters/

> The callback functions attached to the filter hook are invoked by calling this function.

The callback functions change the default values, which is something we need. Previously I was passing the expected values rather than a callback function _returning_ those values.

**Comment by roborourke** [comment]
Yeah that's what I mean - if the calls in this PR were using `add_filter()` then not having a callable as the 2nd argument would be a bug but these are all `apply_filters()` so 2nd argument is the value that is passed to functions using that filter. It was fine as it was as far as I can see.

For example right now this line sets the `$waitfor_consent_hook` variable to the literal string "__return_false":

```php
$waitfor_consent_hook = apply_filters( 'wp_consent_api_waitfor_consent_hook', '__return_false' );
```

It's my bad for not scrutinising the PR more closely originally, apologies for that.

**Comment by jazzsequence** [comment]
But `__return_false` is an actual function that returns...false. Not the value.

```php
function __return_false() { // phpcs:ignore WordPress.NamingConventions.ValidFunctionName.FunctionDoubleUnderscore,PHPCompatibility.FunctionNameRestrictions.ReservedFunctionNames.FunctionDoubleUnderscore
    return false;
}
```
http://developer.wordpress.org/reference/functions/__return_false/

**Comment by roborourke** [comment]
I'm aware of that - I'm saying the 2nd parameter to `apply_filters()` is the actual value you want to filter that is passed to a callback set using `add_filter()`. This is mixing up `apply_filters()` and `add_filter()`.

**Comment by roborourke** [comment]
This is the Xdebug output - I've changed the `$waitfor_consent_hook` value back to false but left the other filters as-is and commented out the filters added to these hooks in the consent plugin. You can see in the upper left panel that the values of the variables are the closure functions themselves rather than the values returned by them.

Screenshot 2021-01-06 at 10 46 16

**Comment by jazzsequence** [comment]
Okay, that does make sense. At some point I need to get Xdebug set up in my VSCode....I will pull down the revert branch and test it locally. Not sure if I was misunderstanding the docs or if there's some other issue that I was seeing...

**Comment by roborourke** [comment]
I imagine it might have been an issue if you had it the other way around by mistake in the consent plugin itself, having a raw value as the 2nd parameter to `add_filter()` that wasn't a valid callback would have thrown up an error that may have led you on a wild goose chase to patch it in the wrong place. Can be easily done, especially when there's a lot going on pandemically and generally.

**Pull request merged**
